### PR TITLE
remove `date_default_set_timezone` call

### LINKED ISSUE #27: Remove `date_default_timezone_set` (or not with "Europe/Paris")
Calling [`date_default_timezone_set`](https://github.com/PaylineByMonext/payline-php-sdk/blob/master/src/Payline/PaylineSDK.php#L354) set the timezone for all datetimes in the script. after the PaylineSdk has been initialized.

It seems that the only purpose of that is to [get the date in the log file name](https://github.com/PaylineByMonext/payline-php-sdk/blob/master/src/Payline/PaylineSDK.php#L361-L363)

As date does not accept a timezone as a parameter, you can use the `DateTime` object, compatible with PHP >= 5.2 (which is lower than your PHP requirement).

### PR DESCRIPTION
**Pull request by jdeniau**
Fixes #27 

The implementation was quite easy, if it's only for the log file name, so I made it myself.

Thanks

### CODE REVIEW

**Comment by jdeniau** [comment]
ping @PaylineGitHub or @ColonelMoutarde maybe ?

**Comment by ColonelMoutarde** [comment]
I don’t Work for payline, i’m only contributor.

**Comment by CharlelieBouvier** [comment]
I'll take a look this week

**Comment by jdeniau** [comment]
@CharlelieBouvier thanks

@ColonelMoutarde sorry, I looked at the contribution chart ;)

**Comment by ColonelMoutarde** [comment]
No problem ;)

**Pull request merged**
