### PR TITLE
php7.4 compatibility

### PR DESCRIPTION
**Pull request by smknstd**
https://www.php.net/manual/fr/migration74.deprecated.php#migration74.deprecated.core.array-key-exists-objects

### CODE REVIEW

**Comment by AntoineLemaire** [comment]
Why the whole file has been changed?
image

**Comment by smknstd** [comment]
I think my IDE switch EOL chars or something. Github let you ignore these :

Screenshot_2020-09-01 php7 4 compatibility by smknstd · Pull Request #64 · PaylineByMonext payline-php-sdk

**Comment by smknstd** [comment]
@AntoineLemaire any news ?

**Comment by AntoineLemaire** [comment]
It seems good for me, but I'm not a owner of this repo, just a contributor.

But I'm still not sure it's good to have all thoses EOL char modifications are good for lisibility. I think we should keep as we had

**Comment by neopheus** [comment]
New PR, without IDE problem : https://github.com/PaylineByMonext/payline-php-sdk/pull/66

**Pull request closed without merging**
