### PR TITLE
Add support monolog v2

### PR DESCRIPTION
**Pull request by RomulusED69**
[issue](https://github.com/PaylineByMonext/payline-php-sdk/issues/49)
@CharlelieBouvier can you test my pr, I replace methods add by methods without exists in v1 and v2.

### CODE REVIEW

**Comment by tristanbes** [comment]
He replaced `add*` methods with `info()` or `error()` which exist both in monolog v1 and monolog v2;

https://github.com/Seldaek/monolog/blob/master/UPGRADE.md

**Comment by CharlelieBouvier** [comment]
Hello, 

Can you push a commit without formatting the whole file please? Juste replace the methods call. Thank you for your PR btw.

**Comment by tristanbes** [comment]
You have blank space everywhere; is it a blocker for you if we leave this way ?
It cleaner this way, it's just spaces stripped; no harm done 🥇

**Comment by CharlelieBouvier** [comment]
Well it makes a huge diff, it is not recommended to format the whole file, only the modified code.
It's not a blocker, leave it that way.

I'll test it asap today.

**Comment by tristanbes** [comment]
Hello, do you have feedbacks ? or is it good to merge and tag a new version please @CharlelieBouvier ?

**Comment by CharlelieBouvier** [comment]
Hello,

I didn't have time to complete my review, I'll look into it this evening

**Pull request merged**
